# Generated by Django 3.2.8 on 2025-03-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('horas_disponibles', models.PositiveIntegerField()),
                ('asignaturas', models.TextField(help_text='Lista de asignaturas separadas por comas')),
            ],
        ),
    ]
