# Generated by Django 5.1.7 on 2025-07-08 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='dia',
        ),
    ]
