# Generated by Django 5.1.7 on 2025-08-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_horario_usuario_horarioguardado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioguardado',
            name='nombre',
            field=models.CharField(default='Horario sin nombre', max_length=100),
        ),
    ]
