# Generated by Django 3.2.8 on 2025-03-14 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_auto_20250313_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('Salón', 'Salón'), ('Laboratorio 4.0', 'Laboratorio 4.0'), ('Sala de Cómputo 1', 'Sala de Cómputo 1'), ('Sala de Cómputo 2', 'Sala de Cómputo 2'), ('Sala de Cómputo 3', 'Sala de Cómputo 3'), ('Sala de Cómputo 4', 'Sala de Cómputo 4'), ('Sala de Cómputo 5', 'Sala de Cómputo 5'), ('Sala de Cómputo 6', 'Sala de Cómputo 6'), ('Sala de Cómputo 7', 'Sala de Cómputo 7'), ('Sala de Cómputo 8', 'Sala de Cómputo 8')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_app.docente'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='asignaturas',
            field=models.ManyToManyField(blank=True, related_name='docentes', to='mi_app.Asignatura'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_app.aula'),
        ),
    ]
