# Generated by Django 5.1.7 on 2025-08-12 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_alter_horarioguardado_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aula',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrerauniversitaria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nodisponibilidad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_disponibilidades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semestre',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('usuario', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='docente',
            unique_together={('usuario', 'correo')},
        ),
    ]
