# Generated by Django 3.2.8 on 2025-03-14 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_auto_20250313_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_asignadas', to='mi_app.docente'),
        ),
    ]
