# Generated by Django 5.1.7 on 2025-03-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_alter_asignatura_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='asignaturas',
        ),
    ]
