# Generated by Django 5.1.7 on 2025-08-12 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_asignatura_usuario_aula_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='docente',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='carrerauniversitaria',
            name='jornadas',
        ),
        migrations.RemoveField(
            model_name='carrerauniversitaria',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='nodisponibilidad',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='semestre',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='aula',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diasemana',
            name='codigo',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='docente',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='nodisponibilidad',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=10),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='mi_app.institucion'),
        ),
        migrations.AddField(
            model_name='aula',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='mi_app.institucion'),
        ),
        migrations.AddField(
            model_name='carrerauniversitaria',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='mi_app.institucion'),
        ),
        migrations.AddField(
            model_name='diasemana',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='mi_app.institucion'),
        ),
        migrations.AddField(
            model_name='docente',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='mi_app.institucion'),
        ),
        migrations.AddField(
            model_name='horario',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='mi_app.institucion'),
        ),
        migrations.AddField(
            model_name='horarioguardado',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_guardados', to='mi_app.institucion'),
        ),
        migrations.AddField(
            model_name='nodisponibilidad',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_disponibilidades', to='mi_app.institucion'),
        ),
        migrations.AddField(
            model_name='semestre',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='mi_app.institucion'),
        ),
        migrations.AddConstraint(
            model_name='asignatura',
            constraint=models.UniqueConstraint(fields=('institucion', 'nombre', 'semestre'), name='uniq_asignatura_nombr_sem_por_institucion'),
        ),
        migrations.AddConstraint(
            model_name='aula',
            constraint=models.UniqueConstraint(fields=('institucion', 'nombre'), name='uniq_aula_por_institucion'),
        ),
        migrations.AddConstraint(
            model_name='carrerauniversitaria',
            constraint=models.UniqueConstraint(fields=('institucion', 'nombre'), name='uniq_carrera_por_institucion'),
        ),
        migrations.AddConstraint(
            model_name='diasemana',
            constraint=models.UniqueConstraint(fields=('institucion', 'codigo'), name='uniq_dia_codigo_por_institucion'),
        ),
        migrations.AddConstraint(
            model_name='diasemana',
            constraint=models.UniqueConstraint(fields=('institucion', 'nombre'), name='uniq_dia_nombre_por_institucion'),
        ),
        migrations.AddConstraint(
            model_name='docente',
            constraint=models.UniqueConstraint(fields=('institucion', 'correo'), name='uniq_docente_correo_por_institucion'),
        ),
        migrations.AddConstraint(
            model_name='semestre',
            constraint=models.UniqueConstraint(fields=('institucion', 'carrera', 'numero'), name='uniq_semestre_por_institucion'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='mi_app.institucion'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='aula',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='usuario',
        ),
    ]
