# Generated by Django 5.1.7 on 2025-03-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0006_remove_docente_asignaturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='asignaturas',
            field=models.ManyToManyField(blank=True, related_name='docentes', to='mi_app.asignatura'),
        ),
    ]
