# Generated by Django 5.1.7 on 2025-08-15 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0006_institucion_perfilusuario_alter_aula_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil usuario', 'verbose_name_plural': 'Perfil usuario'},
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='institucion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='mi_app.institucion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aula',
            name='institucion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='mi_app.institucion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrerauniversitaria',
            name='institucion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='mi_app.institucion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diasemana',
            name='institucion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='mi_app.institucion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docente',
            name='institucion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='mi_app.institucion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horario',
            name='institucion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='mi_app.institucion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horarioguardado',
            name='institucion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_guardados', to='mi_app.institucion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodisponibilidad',
            name='institucion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='no_disponibilidades', to='mi_app.institucion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semestre',
            name='institucion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='mi_app.institucion'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Descanso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('nombre', models.CharField(blank=True, help_text='Opcional (ej. Almuerzo, Pausa)', max_length=80)),
                ('color_hex', models.CharField(default='#FFE0E0', help_text='Color para pintar el descanso en la grilla', max_length=7)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descansos', to='mi_app.diasemana')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descansos', to='mi_app.institucion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descansos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descanso',
                'verbose_name_plural': 'Descansos',
                'ordering': ['dia__orden', 'hora_inicio'],
                'indexes': [models.Index(fields=['institucion', 'usuario'], name='mi_app_desc_institu_7653fc_idx'), models.Index(fields=['institucion', 'usuario', 'dia'], name='mi_app_desc_institu_c44be2_idx')],
            },
        ),
    ]
