# Generated by Django 5.1.7 on 2025-03-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_docente_asignaturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='jornada',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], default='Mañana', max_length=10),
        ),
    ]
