# Generated by Django 5.1.7 on 2025-08-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='intensidad_horaria',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='horas_totales',
            field=models.PositiveIntegerField(default=0, help_text='Horas totales de la asignatura en HORAS INSTITUCIONALES (según la duración de hora definida en la institución).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semanas',
            field=models.PositiveIntegerField(default=16, help_text='Cantidad de semanas en que se verá esta asignatura (≥ 1).'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='duracion_hora_minutos',
            field=models.PositiveIntegerField(choices=[(40, '40 min'), (45, '45 min'), (50, '50 min'), (60, '60 min')], default=45, help_text="Cuántos minutos dura una 'hora institucional' en esta institución. Afecta a TODAS las asignaturas al convertir las horas totales de la asignatura en minutos totales y luego distribuirlos por semana."),
        ),
    ]
