# Generated by Django 5.1.7 on 2025-03-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0008_asignatura_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='intensisdad_horaria',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='numero_encuentros',
            field=models.PositiveIntegerField(default=16),
        ),
    ]
