# Generated by Django 5.1.7 on 2025-03-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0009_asignatura_intensisdad_horaria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='intensisdad_horaria',
            new_name='intensidad_horaria',
        ),
    ]
