# Generated by Django 5.1.7 on 2025-03-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0010_rename_intensisdad_horaria_asignatura_intensidad_horaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='intensidad_horaria',
            field=models.PositiveIntegerField(default=90),
        ),
    ]
