# Generated by Django 5.1.7 on 2025-03-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0011_alter_asignatura_intensidad_horaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='tipo',
        ),
    ]
