# Generated by Django 5.1.7 on 2025-03-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0013_carrerauniversitaria_semestre_asignatura_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrerauniversitaria',
            name='dias_clase',
            field=models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado'), ('DO', 'Domingo')], default='LU,MA,MI,JU,VI', help_text='Selecciona los días en que se imparte esta carrera', max_length=50),
        ),
        migrations.AlterField(
            model_name='carrerauniversitaria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
