# Generated by Django 5.1.7 on 2025-03-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0014_carrerauniversitaria_dias_clase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='carrerauniversitaria',
            name='dias_clase',
        ),
        migrations.AddField(
            model_name='carrerauniversitaria',
            name='dias_clase',
            field=models.ManyToManyField(blank=True, to='mi_app.diasemana'),
        ),
    ]
