# Generated by Django 5.1.7 on 2025-03-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0016_diassemana_docentes_materia_semestres_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='materia',
        ),
        migrations.AddField(
            model_name='horario',
            name='materia',
            field=models.ManyToManyField(to='mi_app.asignatura'),
        ),
    ]
