# Generated by Django 5.1.7 on 2025-03-20 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0017_remove_horario_materia_horario_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.diasemana'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.docente'),
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.AlterField(
            model_name='horario',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.semestre'),
        ),
        migrations.DeleteModel(
            name='DiasSemana',
        ),
        migrations.DeleteModel(
            name='Docentes',
        ),
        migrations.DeleteModel(
            name='Semestres',
        ),
    ]
