# Generated by Django 5.1.7 on 2025-03-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0018_alter_horario_dia_alter_horario_docente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='docente',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='docente',
            field=models.ManyToManyField(blank=True, related_name='asignaturas_asignadas', to='mi_app.docente'),
        ),
    ]
