# Generated by Django 5.1.7 on 2025-03-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0019_remove_asignatura_docente_asignatura_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='numero_encuentros',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='dia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
