# Generated by Django 5.1.7 on 2025-03-27 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0021_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.aula'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='jornada',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=10),
        ),
    ]
