# Generated by Django 5.1.7 on 2025-03-28 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0022_alter_horario_aula_alter_horario_dia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='docente',
            new_name='docentes',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='asignaturas',
        ),
    ]
