# Generated by Django 5.1.7 on 2025-04-06 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0023_rename_docente_asignatura_docentes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('jornada', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_disponibilidades', to='mi_app.docente')),
            ],
            options={
                'unique_together': {('docente', 'dia', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
    ]
