# Generated by Django 5.1.7 on 2025-05-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0024_nodisponibilidad_delete_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='carrerauniversitaria',
            name='jornadas',
            field=models.ManyToManyField(blank=True, related_name='carreras', to='mi_app.jornadas'),
        ),
    ]
