# Generated by Django 5.1.7 on 2025-05-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0025_jornadas_carrerauniversitaria_jornadas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diasemana',
            options={'ordering': ['orden']},
        ),
        migrations.AlterUniqueTogether(
            name='nodisponibilidad',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='diasemana',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
